baseURL = "https://dvorky-9cf82.netlify.com/"
copyright = ""
description = "Basic personal site theme styled with minimal tachyons, syntax highlighting, and blog series configuration."
enableEmoji = true
googleAnalytics = ""
languageCode = "en-us"
theme = "basic"
title = "dvor.ky"
[Permalinks]
post = "post/:slug"
[params]
titleEmoji = ":tada:"
twitter = "siegerts"
[[params.menu]]
name = "blog"
url = "post/"
[[params.menu]]
name = "post series"
url = "series/"
[[params.menu]]
name = "about"
url = "about/"
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true
[taxonomies]
category = "categories"
series = "series"
tag = "tags"
